### ISSUE TITLE
Kubernetes master must be first host on the list

### ISSUE THREAD

**Issue by wiktorn** [geerlingguy/ansible-role-kubernetes#10]
Because of this part of the code:
```
- name: Get the kubeadm join command from the Kubernetes master.
  shell: kubeadm token create --print-join-command
  changed_when: False
  when: kubernetes_role == 'master'
  run_once: True
  register: kubernetes_join_command
```
And the note in [run_once docs](https://docs.ansible.com/ansible/latest/user_guide/playbooks_delegation.html#run-once):
> Any conditional (i.e when:) will use the variables of the ‘first host’ to decide if the task runs or not, no other hosts will be tested.

Means that this recipe will work only, if the kubernetes master is the first host. If it's not the first one, then the `when` will evaluate to `False` and never will be run.

As my Ansible foo is quite low for now, I didn't found (yet) any fix for this

**Comment by wiktorn** [comment]
And I have the other issue connected with the above:

I have a site.yml playbook:
```
- import_playbook: k8s-master.yml
- import_playbook: k8s-nodes.yml
```

And k8s-master.yml looks like that:
```
- hosts: k8s-master
  vars:
    [...]
    kubernetes_role: "master"
  roles:
  - geerlingguy.pip
  - geerlingguy.docker
  - geerlingguy.kubernetes
```
And my k8s-nodes.yml looks as follows:
```
-   hosts: k8s-nodes
  vars:
    [...]
    kubernetes_role: "node"
  roles:
  - geerlingguy.docker
  - geerlingguy.kubernetes
```
In this configuration - kubectl join command will be gathered when running on k8s-master host group, and then again - when running on k8s-nodes host group, which will overwrite the command and the whole setup fails with:

```
fatal: [fc-node-01]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'stdout'\n\nThe error appears to have been in '/home/w/.ansible/roles/geerlingguy.kubernetes/tasks/node-setup.yml': line 2, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n---\n- name: Join node to Kubernetes master\n  ^ here\n"}
````
So I guess the root of the problem is the separation between two groups
