### ISSUE TITLE
Fail to install on fresh OS

### ISSUE THREAD

**Issue by soulraven** [geerlingguy/ansible-role-kubernetes#122]
hello,
i have a test bench with Ubuntu 22.04 with fresh install.

After the first run i get this error:
https://pastebin.com/cqkrpav2

after the second run i get this:
https://pastebin.com/ynN7X677

the playbook is like this:

```yml
- name: Kubernetes deploy
  collections: []
  hosts: [ 'hp_t620' ]
  gather_facts: True
  become: True
  environment: '{{ inventory__environment | d({})
                   | combine(inventory__group_environment | d({}))
                   | combine(inventory__host_environment  | d({})) }}'

  vars:
    pip_install_packages:
      - name: docker
    kubernetes_allow_pods_on_master: true

  pre_tasks:
    - name: Install packages needed for deploy
      package:
        name:
          - apt-utils
        state: latest


  roles:
    - role: geerlingguy.pip
      tags: []
    
    - role: geerlingguy.docker
      tags: []

    - role: geerlingguy.kubernetes
      tags: []
```

docker_compose_version: "v2.6.0"
and
kubernetes_version: '1.24'

any idea what is wrong ?
