### ISSUE TITLE
Support JoinConfiguration

### ISSUE THREAD

**Issue by dkirrane** [geerlingguy/ansible-role-kubernetes#129]
To setup [vSphere CSI](https://cloud-provider-vsphere.sigs.k8s.io/tutorials/kubernetes-on-vsphere-with-kubeadm.html) I need to add the `cloud-provider: external`

For `InitConfiguration` I can use `kubernetes_config_init_configuration`
```
apiVersion: kubeadm.k8s.io/v1beta2
kind: InitConfiguration
nodeRegistration:
  kubeletExtraArgs:
    cloud-provider: external
```

But currently it looks like there is no option for `JoinConfiguration`
```
apiVersion: kubeadm.k8s.io/v1beta2
kind: JoinConfiguration
nodeRegistration:
  kubeletExtraArgs:
    cloud-provider: external
```
