### ISSUE TITLE
Undefined Variable

### ISSUE THREAD

**Issue by wand3r3r** [geerlingguy/ansible-role-kubernetes#13]
Using this role I get an undefined variable when trying to join nodes to master. 
My ansible inventory looks like
```
[master]
master1=<ip>

[worker]
worker1=<ip>
worker2=<ip>

[master:vars]
kubernetes_role="master"
kubernetes_enable_web_ui=True

[worker:vars]
kubernetes_role="node"
```

My ansible play in equally simple (there is a separate play that installs docker).

```
- hosts: all
  remote_user: centos
  vars:
    kubernetes_allow_pods_on_master: False
  tasks:
    - name: Install Kubes
      become: yes
      become_method: sudo
      import_role:
        name: geerlingguy.kubernetes
```
The output is:
```
TASK [geerlingguy.kubernetes : Join node to Kubernetes master] **********************************************************************************************************************
task path: /media/sf_dWork/cf_repos/testKubernets/roles/geerlingguy.kubernetes/tasks/node-setup.yml:2
fatal: [worker1]: FAILED! => {
    "msg": "The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'stdout'\n\nThe error appears to have been in '/testKubernets/roles/geerlingguy.kubernetes/tasks/node-setup.yml': line 2, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n---\n- name: Join node to Kubernetes master\n  ^ here\n"
}
META: noop
fatal: [worker2]: FAILED! => {
    "msg": "The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'stdout'\n\nThe error appears to have been in '/testKubernets/roles/geerlingguy.kubernetes/tasks/node-setup.yml': line 2, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n---\n- name: Join node to Kubernetes master\n  ^ here\n"
}

```
