### ISSUE TITLE
kube-flannel-rbac.yml not found

### ISSUE THREAD

**Issue by desimetallica** [geerlingguy/ansible-role-kubernetes#130]
Hello, I'm trying to use this role to deploy k8s on ubuntu. 
the process is going smooth but it encounter a fail with:

 "item": "kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/k8s-manifests/kube-flannel-rbac.yml"

it returns:

"stderr_lines": [
        "error: unable to read URL \"https://raw.githubusercontent.com/coreos/flannel/master/Documentation/k8s-manifests/kube-flannel-rbac.yml\", server reported 404 Not Found, status code=404"
    ]

For the other item in the task the process is ok: 
 "item": "kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml"

Is it a problem for the deploy?

**Comment by dkirrane** [comment]
I hit this issue also.
Workaround was to override the default vars

```
  vars:

    # Flannel
    kubernetes_flannel_manifest_file_rbac: https://raw.githubusercontent.com/flannel-io/flannel/master/Documentation/kube-flannel.yml
    kubernetes_flannel_manifest_file: https://raw.githubusercontent.com/flannel-io/flannel/master/Documentation/kube-flannel.yml
    kubernetes_pod_network:
      cni: 'flannel'
      cidr: '10.244.0.0/16'
```
