### ISSUE TITLE
Put a hold on packages

### ISSUE THREAD

**Issue by dkirrane** [geerlingguy/ansible-role-kubernetes#131]
My Ubuntu updated the packages.
All packages likely need a hold to avoid surprise upgrades

```
- name: Prevent kubernetes from being upgraded
  dpkg_selections:
    name: "{{ item }}"
    selection: hold
  loop:
    - kubelet
    - kubectl
    - kubeadm
    - kubernetes-cni

- name: Prevent docker from being upgraded
  dpkg_selections:
    name: "{{ item }}"
    selection: hold
  loop:
    - docker-ce
    - docker-ce-cli
    - docker-ce-rootless-extras
    - containerd.io

```
