### ISSUE TITLE
`kubernetes-join-command` not delegated to any host except master

### ISSUE THREAD

**Issue by iLem0n** [geerlingguy/ansible-role-kubernetes#145]
Trying to bring up a simple k8s cluster with one master and one worker node. 

Just bringing them up using vagrant brings me to the following problem: 
It seems that the `kubernetes-join-command` is only be set on the master node not the worker ones. 
Which results in failure ad worker provisioning. 

Versions:
```
# VAGRANT: 
Vagrant 2.3.4
# ANSIBLE: 
ansible [core 2.14.1]
  config file = /Users/ilem0n/projects_NEW/multiserver-cluster-setup/node-config/ansible.cfg
  configured module search path = ['/Users/ilem0n/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.10/site-packages/ansible
  ansible collection location = /Users/ilem0n/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.10.10 (main, Feb  8 2023, 05:40:53) [Clang 14.0.0 (clang-1400.0.29.202)] (/usr/local/opt/python@3.10/bin/python3.10)
  jinja version = 3.1.2
  libyaml = True
```

Vagrant file:
```ruby
IMAGE_NAME = "debian/bullseye64"
N = 1    
SYSTEM_USER = "vagrant"

Vagrant.configure("2") do |config|
    config.ssh.insert_key = false
    
    config.vm.provider "virtualbox" do |node|
        node.memory = 2056
        node.cpus = 2
    end
      
    config.vm.define "kubernetes-master" do |master|
        master.vm.box       = IMAGE_NAME
        master.vm.network   "private_network", ip: "192.168.0.10"
        master.vm.network   "forwarded_port", guest: 80, host: 80
        master.vm.network   "forwarded_port", guest: 443, host: 443
        master.vm.network   "forwarded_port", guest: 6443, host: 6443    

        master.vm.hostname  = "kubernetes-master"

        master.vm.provision "ansible" do |ansible|
            ansible.verbose                 = "vvv"
            ansible.playbook                = "master-playbook.yml"
            ansible.extra_vars              = {
                role: "control_plane",
                node_ip: "192.168.0.10"            
            }
        end
    end

    (1..N).each do |i|
        config.vm.define "kubernetes-worker-#{"%02d" % i}" do |node|
            node.vm.box = IMAGE_NAME
            node.vm.network "private_network", ip: "192.168.56.#{i + 10}"
            node.vm.hostname = "kubernetes-worker-#{"%02d" % i}"
            node.vm.provision "ansible" do |ansible|
                ansible.verbose = "vvv"
                ansible.playbook = "master-playbook.yml"
                ansible.extra_vars = {
                    role: "node",
                    node_ip: "192.168.56.#{i + 10}"
                }
            end
        end
    end
end
```

`master-playbook.yml`
```yaml
---
- hosts: all
  name: Kubernetes configuration
  become: true
  gather_facts: true

  vars:
   system_user: ilem0n

  collections:
    - geerlingguy.k8s
    - kubernetes.core

  pre_tasks:
    - name: Preparation
      ansible.builtin.include_tasks: sub-tasks/pre-tasks.yml

  roles:
    - helm
    - andrewrothstein.k9s
    - geerlingguy.containerd
    - role: geerlingguy.ntp
      ntp_timezone: Europe/Berlin
    - role: geerlingguy.kubernetes
      kubernetes_role: "{{ role }}"
      kubernetes_config_init_configuration:
        localAPIEndpoint:
          advertiseAddress: "{{ kubernetes_apiserver_advertise_address | default(ansible_default_ipv4.address, true) }}"
```

join-command setup:
```
...
TASK [geerlingguy.kubernetes : Set the kubeadm join command globally.] *********
task path: /Users/ilem0n/.ansible/roles/geerlingguy.kubernetes/tasks/main.yml:48
ok: [kubernetes-master] => (item=kubernetes-master) => {
    "ansible_facts": {
        "kubernetes_join_command": "kubeadm join 10.0.2.15:6443 --token dbdld5.4djx6olxur7zswo7 --discovery-token-ca-cert-hash sha256:2d2a27846899fa8f9b731bf416147edd806e1d8b27a93ff7513085e9f893508d  \n"
    },
    "ansible_loop_var": "item",
    "changed": false,
    "item": "kubernetes-master"
}
...
```

nodes tries to use join-command:
```
...
TASK [geerlingguy.kubernetes : Join node to Kubernetes control plane.] *********
task path: /Users/ilem0n/.ansible/roles/geerlingguy.kubernetes/tasks/node-setup.yml:2
fatal: [kubernetes-worker-01]: FAILED! => {
    "msg": "The task includes an option with an undefined variable. The error was: 'kubernetes_join_command' is undefined. 'kubernetes_join_command' is undefined\n\nThe error appears to be in '/Users/ilem0n/.ansible/roles/geerlingguy.kubernetes/tasks/node-setup.yml': line 2, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n---\n- name: Join node to Kubernetes control plane.\n  ^ here\n"
}
...
```
