### ISSUE TITLE
Upgrading packages from 1.29 to 1.30 breaks the repo

### ISSUE THREAD

**Issue by FireDrunk** [geerlingguy/ansible-role-kubernetes#163]
When upgrading from 1.29 to 1.30 something broke in the setup of the Kubernetes APT Repositories on my Debian machines.

Environment:
- Debian 12 fully patched
- Ansible venv running ansible 10.7, ansible-core 2.17.11
- geerlingguy.docker 1.3.1
- geerlingguy.kubernetes 8.1.0

include YAML:
```yaml
---
- import_role:
    name: geerlingguy.kubernetes
  vars:
    kubernetes_packages:
      - name: kubelet
        state: latest
      - name: kubectl
        state: latest
      - name: kubeadm
        state: latest
      - name: kubernetes-cni
        state: latest
    kubernetes_version: 1.30
    kubernetes_role: none
```

Resulting error:

```
The full traceback is:
  File "/tmp/ansible_deb822_repository_payload_f03n0v7d/ansible_deb822_repository_payload.zip/ansible/modules/deb822_repository.py", line 516, in main
  File "/tmp/ansible_deb822_repository_payload_f03n0v7d/ansible_deb822_repository_payload.zip/ansible/modules/deb822_repository.py", line 331, in write_signed_by_key
  File "<string>", line 3, in raise_from
fatal: [m2]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "allow_downgrade_to_insecure": null,
            "allow_insecure": null,
            "allow_weak": null,
            "architectures": null,
            "by_hash": null,
            "check_date": null,
            "check_valid_until": null,
            "components": null,
            "date_max_future": null,
            "enabled": null,
            "inrelease_path": null,
            "languages": null,
            "mode": "0644",
            "name": "kubernetes",
            "pdiffs": null,
            "signed_by": "https://pkgs.k8s.io/core:/stable:/v1.3/deb//Release.key",
            "state": "present",
            "suites": [
                "/"
            ],
            "targets": null,
            "trusted": null,
            "types": [
                "deb"
            ],
            "uris": [
                "https://pkgs.k8s.io/core:/stable:/v1.3/deb/"
            ]
        }
    },
    "msg": "Could not fetch signed_by key: HTTP Error 403: Forbidden"
}
```

It looks like it's building the URI incorrectly, but I'm not sure what the proper URI should be.
