### ISSUE TITLE
add kubectl bash completion

### ISSUE THREAD

**Issue by rdxmb** [geerlingguy/ansible-role-kubernetes#23]
This is a FEATURE REQUEST.
Could we add bash_completion for kubectl in this repository? I think this could be done via

```
    - name: add kubectl bash completion
      lineinfile:
        path: ~/.bashrc
        line: source <(kubectl completion bash)
        state: present
```
