### ISSUE TITLE
Deployment fails with Vagrant centos/7

### ISSUE THREAD

**Issue by ybizeul** [geerlingguy/ansible-role-kubernetes#48]
I'm trying to use this role as a provisioning configuration for Vagrant, with a base Centos/7 box.

A few things that the role should do :

- Make sure swap is disabled
- Make sure `net.bridge.bridge-nf-call-iptables` is `1`

Here is a role I use between `geerlingguy.docker` and `geerlingguy.kubernetes` as a workaround

```
---
# tasks file for prepare-kubernetes
- name: Disable swap
  replace:
    path: /etc/fstab
    regexp: '(^[^#].* swap .*)'
    replace: '#\1'
  register: swap

- name: Disable swap runtime
  command: "swapoff -a"
  when: swap.changed
  
- name: Set bridge-nf-call-iptables
  sysctl:
    name: net.bridge.bridge-nf-call-iptables
    value: 1
    sysctl_set: yes
    state: present
    reload: yes
```
