### ISSUE TITLE
Feature Request - Disable Swap

### ISSUE THREAD

**Issue by ernestomedina17** [geerlingguy/ansible-role-kubernetes#61]
Hello Jeff

```
- name: Remove swap from /etc/fstab
  lineinfile:
    dest: /etc/fstab
    regexp: '^.* swap .*$'
    state: absent
- name: Disable swap
  command: swapoff -a
  when: ansible_swaptotal_mb > 0
```

It would be nice to execute those tasks to disable Swap before installing Kubelet as it fails to start if Swap is enabled.

**Comment by rafilkmp3** [comment]
```
  - name: Remove swapfile from /etc/fstab
    mount:
      name: swap
      fstype: swap
      state: absent
      
  - name: Disable swap
    shell: swapoff -a
    when: ansible_swaptotal_mb > 0
```
